services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - TZ=Etc/UTC
    volumes:
      - /elysium/resilio-config:/config:Z
      - /elysium/resilio-cache:/downloads:Z
      - /elysium/resilio-data:/sync:Z
    restart: unless-stopped
    networks:
      - caddy_net
    read_only: true
    cap_drop:
      - "ALL"
    cap_add:
      - "DAC_OVERRIDE"
      - "SETUID"
      - "SETGID"
    security_opt:
      - "no-new-privileges=true"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      io.containers.autoupdate: "registry"

networks:
  caddy_net:
    name: caddy_net
    external: true