services:
  ebook2audiobookpiper:  
    image: ghcr.io/pinoykrissmith/ebook2audiobookpiper:latest
    container_name: ebook2audiobookpiper
    user: "200011:200011"
    volumes:
      - /elysium/ebook2audiobookpiper-data:/app:Z
    tmpfs:
      - /app/Working_files:mode=777,noexec,nosuid,nodev
      - /app/Chapter_wav_files:mode=777,noexec,nosuid,nodev
      - /tmp:mode=777,noexec,nosuid,nodev
    read_only: true
    cap_drop:
      - "ALL"
    security_opt:
      - "no-new-privileges=true"
    tty: true
    networks:
      - caddy_net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      io.containers.autoupdate: "registry"

networks:
  caddy_net:
    name: caddy_net
    external: true