app = "uptime-kuma-tailscale-asahi"
primary_region = "ewr"

[[mounts]]
  source = "data"
  destination = "/app/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[checks]
  [checks.uptime_kuma_check]
    grace_period = "30s"
    interval = "15s"
    port = 3001
    timeout = "10s"
    type = "tcp"


[[services]]
  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.http]]
    internal_port = 3001
    force_https = true
    allow = ["100.64.0.0/10"]

  [[services.ports]]
    handlers = []
    port = "80"

[http_service]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpu_kind = "shared"