app = "uptime-kuma-tailscale-asahi"

[[mounts]]
  source = "data"
  destination = "/app/data"

[[mounts]]
  source = "tailscale"
  destination = "/var/lib/tailscale"

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[[services]]
  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.http]]
    internal_port = 3001
    force_https = true
    allow = ["100.64.0.0/10"]

  [[services.ports]]
    handlers = []
    port = "80"

[http_service]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]