services:
  fdroid:
    image: ghcr.io/pinoykrissmith/containers:fdroid
    container_name: fdroid
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - ./apks.json:/apks.json:Z,ro
      - ./metadata:/fdroid/metadata:Z
      - ./keystore.p12:/keystore.p12:Z,ro
      - /elysium/fdroid-data:/fdroid/repo:Z
      - /elysium/fdroid-cache:/cache:Z
    user: "101:101"
    cap_drop:
      - "ALL"
    security_opt:
      - "no-new-privileges=true"
    read_only: true
    env_file:
      - .env
    environment:
      - REPO_URL=${REPO_URL}
      - REPO_NAME=${REPO_NAME}
      - KEYSTOREPASS=${KEYSTOREPASS}
      - KEYPASS=${KEYPASS}
    networks:
      caddy_net:
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      io.containers.autoupdate: "registry"
    tmpfs:
      - /fdroid:mode=777,nodev,noexec,nosuid

networks:
  caddy_net:
    name: caddy_net
    external: true