services:
    nitter:
      image: ghcr.io/pinoykrissmith/nitter:latest
      container_name: nitter
      user: "200013:200013"
      labels:
        com.centurylinklabs.watchtower.enable: "true"
        io.containers.autoupdate: "registry"
      volumes:
        - ./nitter.conf:/app/nitter.conf:Z,ro
        - /elysium/nitter-data:/data:Z
      depends_on:
        nitter-redis:
          condition: service_healthy
      restart: unless-stopped
      cap_drop:
        - "ALL"
      security_opt:
        - "no-new-privileges=true"
      read_only: true
      network_mode: service:nitter-gluetun

    nitter-redis:
      image: ghcr.io/polarix-containers/redis:6
      container_name: nitter-redis
      command: redis-server --save 60 1 --loglevel warning
      volumes:
        - /elysium/nitter-redis:/data:Z
      restart: unless-stopped
      networks:
        - caddy_net
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 5s
        retries: 12
      user: "200009:200009"
      read_only: true
      security_opt:
        - "no-new-privileges=true"
      cap_drop:
        - ALL
      environment:
        LD_PRELOAD: ""
      labels:
        com.centurylinklabs.watchtower.enable: "true"
        io.containers.autoupdate: "registry"

    nitter-gluetun:
      image: docker.io/qmcgaw/gluetun:latest
      container_name: nitter-gluetun
      restart: always
      tty: true
      read_only: true
      labels:
        com.centurylinklabs.watchtower.enable: "true"
        io.containers.autoupdate: "registry"
      cap_drop:
        - ALL
      cap_add:
        - NET_ADMIN
        - DAC_OVERRIDE
        - CHOWN
        - SETUID
        - SETGID
      security_opt:
        - "no-new-privileges=true"
        - "label=disable"
      networks:
        - caddy_net  
      devices:
        - /dev/net/tun:/dev/net/tun
      env_file:
        - .env  
      environment:
        - TZ=Europe/Paris
        - FREE_ONLY=true
        - DNS_KEEP_NAMESERVER=true
      volumes:
        - ./passwd:/etc/passwd:Z
      tmpfs:
        - /gluetun:noexec,nosuid,nodev
        - /tmp:noexec,nosuid,nodev
        - /etc/openvpn:noexec,nosuid,nodev

networks:
  caddy_net:
    name: caddy_net
    external: true