name: Deploy Uptime Kuma
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-uptime-kuma.yml'
      - 'Uptime_Kuma/Dockerfile'
      - 'Uptime_Kuma/fly.toml'
      - 'Uptime_Kuma/supervisord.conf'
  schedule:
    # Build the image weekly
    - cron: '15 0 * * 5'
    
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-24.04
    concurrency: deploy-group
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
        working-directory: Uptime_Kuma
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_UPTIME_KUMA }}